Imports System.Globalization

Namespace Models
   ''' <summary>
   ''' Application Information - Centralized app details
   ''' </summary>
   Public Class AppInfo
      ' Application Details
      Public Shared ReadOnly Property AppName As String = "SalesPro"
      Public Shared ReadOnly Property AppFullName As String = "SalesPro - Smart Business Manager"
      Public Shared ReadOnly Property AppVersion As String = "2.0.0"
      Public Shared ReadOnly Property AppDescription As String = "A comprehensive business management system featuring inventory, sales, purchases, and advanced reporting capabilities."

      ' Company/Developer Details
      Public Shared ReadOnly Property DeveloperName As String = "Nandang Duryat"
      Public Shared ReadOnly Property DeveloperNIM As String = "312310233"
      Public Shared ReadOnly Property DeveloperClass As String = "TI.23.B1"
      Public Shared ReadOnly Property University As String = "Pelita Bangsa"
      Public Shared ReadOnly Property Course As String = "Pemrograman Visual (Desktop)"
      Public Shared ReadOnly Property Lecturer As String = "Asep Muhidin, S.Kom., M.Kom."
      Public Shared ReadOnly Property Copyright As String = $"© {DateTime.Now.Year} {DeveloperName}. All Rights Reserved."

      ' Culture Settings - Use ApplicationSettings for actual values
      Public Shared Function GetIndonesianCulture() As CultureInfo
         Return ApplicationSettings.GetInstance().GetCultureInfo()
      End Function

      ' Export/Print Footer Template
      Public Shared Function GetPrintFooter(Optional includeTimestamp As Boolean = True) As String
         Dim footer As String = $"Generated by {AppFullName} v{AppVersion} | {Copyright}"
         If includeTimestamp Then
            footer &= $" | Generated: {DateTime.Now.ToString(ApplicationSettings.GetInstance().DateTimeFormat)}"
         End If
         Return footer
      End Function

      ' PDF/CSV Metadata
      Public Shared Function GetDocumentMetadata() As String
         Return $"{AppFullName} v{AppVersion}" & vbCrLf &
                $"Developer: {DeveloperName} ({DeveloperNIM})" & vbCrLf &
                $"{University} - {DeveloperClass}"
      End Function

      ' Window Title Format
      Public Shared Function GetWindowTitle(pageTitle As String, Optional username As String = "") As String
         If String.IsNullOrEmpty(username) Then
            Return $"{pageTitle} - {AppName} v{AppVersion}"
         Else
            Return $"{pageTitle} - {AppName} v{AppVersion} | {username}"
         End If
      End Function

      ' Format Currency
      Public Shared Function FormatCurrency(amount As Decimal) As String
         Return amount.ToString("C2", GetIndonesianCulture())
      End Function

      ' Format Date
      Public Shared Function FormatDate(dateValue As DateTime) As String
         Return dateValue.ToString(ApplicationSettings.GetInstance().DateFormat)
      End Function

      ' Format DateTime
      Public Shared Function FormatDateTime(dateValue As DateTime) As String
         Return dateValue.ToString(ApplicationSettings.GetInstance().DateTimeFormat)
      End Function
   End Class
End Namespace
